#!/usr/bin/env bash
# Keeps the "G8 counts" table in docs/cicd.md equal to what the scans report.
#   --check   exit 1 if the table is out of date (used by the G8 gate)
#   --write   rewrite the table (run this locally after changing anything
#             the table counts, then commit docs/cicd.md)
set -euo pipefail

MODE="${1:---check}"
DOC=docs/cicd.md
FIXTURE=tests/security/log_redaction_security.php

# --write is run by a person, so make sure the reports are fresh.
if [ "$MODE" = "--write" ]; then
  ci/scripts/phase-02-secrets.sh > /dev/null 2>&1
fi

open=$(jq 'length' reports/gitleaks.json)
total=$(jq 'length' reports/gitleaks-unfiltered.json)
fixture=$(jq --arg f "$FIXTURE" '[.[] | select(.File == $f)] | length' reports/gitleaks.json)
exceptions=$(jq '.exceptions | length' ci/dependency-exceptions.json)

new_block=$(cat <<TABLE
<!-- g8-counts:start (generated by ci/scripts/docs-counts.sh, do not edit by hand) -->
| What | Count |
|---|---|
| QA dummy secrets allowlisted in \`.gitleaks.toml\` | $((total - open)) |
| Open gitleaks findings (must be 0 for G8 to pass) | $open |
| of which in \`$FIXTURE\` | $fixture |
| Active entries in \`ci/dependency-exceptions.json\` | $exceptions |
<!-- g8-counts:end -->
TABLE
)

old_block=$(sed -n '/<!-- g8-counts:start/,/<!-- g8-counts:end -->/p' "$DOC")

if [ "$MODE" = "--check" ]; then
  if [ "$old_block" = "$new_block" ]; then
    exit 0
  fi
  diff <(echo "$old_block") <(echo "$new_block") | grep '^[<>]' | sed 's/^</docs:  /; s/^>/actual:/'
  exit 1
fi

# --write: replace the block in place.
tmp=$(mktemp)
awk -v block="$new_block" '
  /<!-- g8-counts:start/ { print block; skipping = 1; next }
  /<!-- g8-counts:end -->/ { skipping = 0; next }
  !skipping { print }
' "$DOC" > "$tmp"
mv "$tmp" "$DOC"
echo "docs-counts: $DOC updated"
